include $(ROOT)/etc/config.mk

all:
	@ $(CXX) $(CXXFLAGS) -c $(HERE)/memory.cpp -o $(BIN)/memory.o
	@ $(CXX) $(CXXFLAGS) -c $(HERE)/e820.cpp -o $(BIN)/e820.o
	@ $(CXX) $(CXXFLAGS) -c $(HERE)/e820.s -o $(BIN)/e820.s.o