name: CI

on: [push]

jobs:
  build-x86-64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: |
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        sudo apt-get update
    - run: pip install meson
    - run: meson buildx86 --cross-file x86-64-cross.ini
    - name: Generate kernel image
      run: ninja -C buildx86
    - name: Publish kernel to github
      uses: actions/upload-artifact@v1
      with:
        name: bezos.bin
        page: buildx86/bezos.bin
